//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBPersonnelFile.JXCClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JXCClient.IJXCService")]
    public interface IJXCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJXCService/DoWork", ReplyAction="http://tempuri.org/IJXCService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJXCService/GetServerTime", ReplyAction="http://tempuri.org/IJXCService/GetServerTimeResponse")]
        System.DateTime GetServerTime(int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJXCService/GetTable", ReplyAction="http://tempuri.org/IJXCService/GetTableResponse")]
        System.Data.DataTable GetTable(string Sqlstr, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJXCService/ExecSQL", ReplyAction="http://tempuri.org/IJXCService/ExecSQLResponse")]
        int ExecSQL(string Sqlstr, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJXCService/ExecuteScalar", ReplyAction="http://tempuri.org/IJXCService/ExecuteScalarResponse")]
        object ExecuteScalar(string Sqlstr, int uid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJXCServiceChannel : HBPersonnelFile.JXCClient.IJXCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JXCServiceClient : System.ServiceModel.ClientBase<HBPersonnelFile.JXCClient.IJXCService>, HBPersonnelFile.JXCClient.IJXCService {
        
        public JXCServiceClient() {
        }
        
        public JXCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JXCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JXCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JXCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.DateTime GetServerTime(int uid) {
            return base.Channel.GetServerTime(uid);
        }
        
        public System.Data.DataTable GetTable(string Sqlstr, int uid) {
            return base.Channel.GetTable(Sqlstr, uid);
        }
        
        public int ExecSQL(string Sqlstr, int uid) {
            return base.Channel.ExecSQL(Sqlstr, uid);
        }
        
        public object ExecuteScalar(string Sqlstr, int uid) {
            return base.Channel.ExecuteScalar(Sqlstr, uid);
        }
    }
}
